"""Run the complete release pipeline in a disposable tree, leaving release/ alone.

Uses existing local npm dependencies; does not install or download anything.
Run with .venv/bin/python tests/smoke_release.py.
"""
import hashlib
import json
import shutil
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path
from urllib.parse import parse_qs, urlsplit

from bs4 import BeautifulSoup

ROOT = Path(__file__).resolve().parents[1]


def main():
    catalog = json.loads((ROOT / 'shop/catalog.json').read_text())
    release_before = {str(p.relative_to(ROOT / 'release')): hashlib.sha256(p.read_bytes()).hexdigest()
                      for p in (ROOT / 'release').rglob('*') if p.is_file()}
    with tempfile.TemporaryDirectory(prefix='muckova-release-smoke-') as directory:
        workspace = Path(directory)
        for filename in ['release.py', 'build_shop.py', 'main.css', 'blog.css', 'shop.css',
                         'index.js', 'blog.js', 'shop.js', 'form.js', 'favicon.ico', 'robots.txt',
                         'BingSiteAuth.xml']:
            shutil.copy2(ROOT / filename, workspace / filename)
        for verification in ROOT.glob('seznam-*.txt'):
            shutil.copy2(verification, workspace / verification.name)
        shutil.copytree(ROOT / 'shop', workspace / 'shop')
        (workspace / 'assets').symlink_to(ROOT / 'assets', target_is_directory=True)
        for language in catalog['languages']:
            shutil.copytree(ROOT / language, workspace / language)
        for tool_dir in ('cssnano', 'terser', 'html-minifier'):
            target = workspace / tool_dir
            target.mkdir()
            for source in (ROOT / tool_dir).iterdir():
                if source.is_file() and source.suffix in ('.json', '.js'):
                    shutil.copy2(source, target / source.name)
            (target / 'node_modules').symlink_to(ROOT / tool_dir / 'node_modules', target_is_directory=True)
        (workspace / 'backend').mkdir()
        # Non-secret fixtures must neither be copied nor regenerated by release.py.
        backend_sources = {
            '.htaccess': 'Header always set X-Site-Release "{{RELEASE_VERSION}}"\n',
            '.user.ini': 'post_max_size=16M\n',
            'order_form_handler.php': '<?php // separately deployed endpoint\n',
            'order_mail.php': '<?php // separately deployed mail template\n',
            'order_catalog.php': '<?php // separately generated catalogue\n',
        }
        for filename, content in backend_sources.items():
            (workspace / 'backend' / filename).write_text(content)
        subprocess.run([sys.executable, 'release.py', 'main', 'shop-smoke-test'], cwd=workspace, check=True)
        release = workspace / 'release'
        for filename in ('shop.css', 'shop.js', 'form.js', 'sitemap.xml'):
            assert (release / filename).stat().st_size > 0, filename
        photo_names = {Path(image['src']).name for product in catalog['products']
                       for image in product.get('images', [])}
        supplied_names = {path.name for path in (ROOT / 'assets/desktop').glob('eshop-*')}
        assert len(supplied_names) == 20
        assert supplied_names == photo_names | {'eshop-placeholder.webp'}
        for name in supplied_names:
            assert (release / 'assets/desktop' / name).read_bytes() == (ROOT / 'assets/desktop' / name).read_bytes()
        for path in release.rglob('*'):
            assert path.suffix.lower() != '.php', path
            assert not {'backend', '.htaccess', '.user.ini'}.intersection(part.lower() for part in path.relative_to(release).parts), path
        for filename, content in backend_sources.items():
            assert (workspace / 'backend' / filename).read_text() == content, filename
        assert 'position:sticky' in (release / 'shop.css').read_text().replace(' ', '')
        for language in catalog['languages']:
            soup = BeautifulSoup((release / language / 'shop.html').read_text(), 'html.parser')
            assert len(soup.select('.shop-product')) == len(catalog['products']), language
            assert soup.select_one('#catalog > .shop-catalog-notes + .shop-grid')
            assert soup.select_one('link[rel=canonical]')['href'].endswith(f'/{language}/shop')
            assert all(image['src'].startswith('https://cdn.jsdelivr.net/gh/pmuckova/site-petramuckova.cz@main/') for image in soup.select('.shop-product img'))
            assert not soup.select('[data-placeholder], .shop-photo-placeholder')
            assert 'eshop-placeholder.webp' not in str(soup)
            config = json.loads(soup.select_one('#shop-config').string)
            form = soup.select_one('#shop-order-form')
            assert form['action'] == '/backend/order_form_handler.php'
            assert form['method'] == 'post' and form['enctype'] == 'multipart/form-data'
            assert len(form.select('input[type=file][name="attachment[]"]')) == 3
            assert not soup.select('#order-draft, #order-mailto, #order-copy')
            assert len(config['catalogVersion']) == 64
            assert config['locale'] == language
            assert all(product['price'] == catalog['products'][index]['price'] for index, product in enumerate(config['products']))
            configured_prices = {
                product['id']: [profile['price'] for profile in product['wizard']['profiles']]
                for product in config['products'] if product.get('kind') == 'wizard'
            }
            assert configured_prices == {
                'skoda-ohv-camshaft': [5600, 5600, 11400, 11400, 13200, 11400],
                'taz-camshaft': [4400, 4400, 11500, 15500],
            }
            assert soup.select_one('.shop-product > .article-header > h3.article-title.shop-product-title')
            for card in soup.select('.shop-product'):
                source_product = next(product for product in catalog['products'] if product['id'] == card['id'])
                wizard = card.select_one('form[data-wizard]')
                has_description = bool(source_product['translations'][language]['description'])
                has_photo = bool(source_product.get('image'))
                paragraphs = [p for p in source_product['translations'][language]['description'].split('\n\n') if p.strip()]
                has_body = bool(has_photo or len(paragraphs) > 1 or card['id'] == 'exhaust-headers')
                assert len(card.find_all(recursive=False)) == 3 + has_body
                assert card.find(recursive=False).name == 'header'
                assert card.select_one(':scope > header > .meta-tags > .sys-tag')
                assert card.select_one(':scope > .tech-divider')
                assert bool(card.select_one(':scope > .article-body > .shop-photo img')) == has_photo
                assert ('shop-no-photo' in card['class']) == (not has_photo)
                if not has_photo:
                    assert not card.select('figure, img, .shop-photo-link, .tech-frame, figcaption')
                assert bool(card.select_one(':scope > header .lead')) == has_description
                assert len(card.select('.shop-description')) == len(paragraphs)
                assert not card.select('.article-body form, .tech-table')
                if wizard:
                    assert len(wizard.select('input[name=profile]')) == len(source_product['wizard']['profiles'])
                    expected_fields = source_product['wizard']['fields']
                    assert len(wizard.select('input[type=number][required]')) == sum(
                        field['type'] == 'number' and field['required'] for field in expected_fields)
                    assert len(card.select('.shop-description')) == len(
                        source_product['translations'][language]['description'].split('\n\n'))
                    assert wizard.select_one('button[type=submit].btn-submit')
                    assert not wizard.select('.mandatory-note, [id$="-profile-title"]')
                    bearing = wizard.select_one('[data-bearing]')
                    profile_fields = wizard.select_one('.shop-profile-table > tbody[data-profile-fields][hidden]')
                    assert profile_fields
                    if source_product['wizard']['bearings']:
                        assert bearing and profile_fields.select_one(':scope > tr[data-bearing-fields][hidden]')
                    else:
                        assert not bearing and not wizard.select('[data-bearing-fields]')
                    assert not wizard.select(':scope > h4.form-section-title')
                    profiles = wizard.select_one(':scope > fieldset.shop-profile-options:not([aria-labelledby])')
                    assert profiles
                    assert wizard.find(recursive=False) is profiles
                    legend = profiles.find('legend', recursive=False)
                    assert legend['class'] == ['shop-sr-only']
                    assert legend.get_text() == config['text']['configure']
                    assert len(profiles.select('thead > tr > th')) == 4
                    for option in profiles.select('tbody.shop-profile-option'):
                        rows = option.find_all('tr', recursive=False)
                        assert len(rows) == 2
                        cells = rows[0].find_all('td', recursive=False)
                        assert len(cells) == 4
                        assert cells[0].select_one('input[type=radio]')
                        assert [cell['rowspan'] for cell in cells[1:]] == ['2', '2', '2']
                        assert 'shop-profile-price' in cells[-1]['class']
                        assert len(rows[1].find_all('td', recursive=False)) == 1
                        assert rows[1].select_one('td > .shop-profile-description')
                    field_rows = profile_fields.select(':scope > tr.shop-engine-field')
                    assert len(field_rows) == len(expected_fields)
                    assert all(row.th['scope'] == 'row' and row.td['colspan'] == '3' for row in field_rows)
                    assert [field['name'] for field in profile_fields.select('[data-engine-field]')] == [
                        field['id'] for field in expected_fields]
                    assert all(field.has_attr('disabled') for field in profile_fields.select('[data-engine-field]'))
                    assert 'Ø' not in wizard.get_text()
                    assert not card.select('[data-quantity], [data-change]')
                else:
                    item_form = card.select_one('form[data-order-product]')
                    assert item_form.select_one('table.shop-profile-table input[type=radio][name=option]')
                    assert item_form.select_one('tbody[data-profile-fields][hidden] input[data-order-quantity][disabled]')
                    assert item_form.select_one('tbody[data-profile-fields] button[type=submit].btn-submit[disabled]')
                    assert not card.select('.shop-prices, .shop-product-order, [data-change], [data-quantity]')
                    assert not card.select('.shop-dealer-minimum')
                    assert item_form.select_one('input[data-order-quantity]')['max'] == '9999'
                    spinner = item_form.select_one('.shop-quantity')
                    assert [button['data-order-change'] for button in spinner.select('button[type=button][disabled]')] == ['-1', '1']
                    quantity = spinner.select_one('input[data-order-quantity]')
                    assert item_form.find(id=quantity['data-warning-id'])
                    assert len(item_form.select('thead th')) == 2
                    if source_product['id'] == 'distributor-rotor':
                        assert len(item_form.select('[data-order-field-row="custom"][hidden] input[required][disabled]')) == 2
                    if source_product['id'] == 'head-gasket':
                        assert item_form.select_one('[data-order-field="spacing"][type=text][required][disabled]')
                        assert item_form.select_one('[data-order-field="thickness"][type=number][step=any][data-positive][required][disabled]')
                        gasket = next(product for product in config['products'] if product['id'] == 'head-gasket')
                        custom = next(option for option in gasket['options'] if option['id'] == 'custom')
                        assert custom['price'] is None and custom['priceType'] == 'quote'
                photo_links = card.select('.shop-photo-link')
                for photo_link in photo_links:
                    assert photo_link['href'] == photo_link.img['src']
                    assert photo_link.select_one(':scope > .blog-img-frame > .shop-photo-viewport > img.blog-img')
                if source_product.get('images'):
                    assert bool(card.select_one('.shop-photo-gallery')) == (len(source_product['images']) > 1)
                    assert len(photo_links) == len(source_product['images'])
                    for photo_link, source_image in zip(photo_links, source_product['images']):
                        assert photo_link['href'].endswith(source_image['src'])
                        assert photo_link.img['alt'] == source_image['alt'][language]
                        assert (int(photo_link.img['width']), int(photo_link.img['height'])) == (source_image['width'], source_image['height'])
                        relative_path = source_image['src'].lstrip('/')
                        assert (release / relative_path).read_bytes() == (ROOT / relative_path).read_bytes()
                assert len(card.select('.blog-img-frame')) == len(photo_links)
                assert not card.select('.tech-frame')
            assert soup.select_one('dialog#shop-lightbox.lightbox-modal .lightbox-img')
            for selector, label in (('.shop-lightbox-prev', 'previousPhoto'), ('.shop-lightbox-next', 'nextPhoto')):
                arrow = soup.select_one(f'#shop-lightbox {selector}[hidden]')
                assert arrow and arrow['aria-label'] == config['text'][label]
            assert soup.select_one('script[src*="choices.js@11.1.0"][defer]')
            assert soup.select_one('link[href*="choices.js@11.1.0"]')
            assert len(soup.select('select[data-order-variant]')) == sum(len(option['variantIds']) > 1 for p in catalog['products'] for option in p.get('options', []))
            assert urlsplit(soup.select_one('#navLinks > li > a.active-link')['href']).path == f'/{language}/shop'
            panels = soup.select_one('main .shop-layout > .shop-sidebar > .shop-sidebar-panels')
            assert panels
            assert [child['id'] for child in panels.find_all(recursive=False)] == ['shop-contents', 'basket']
            assert panels.select_one('#basket.toc-wrapper')
            info = soup.select_one('#basket-price-info[hidden][role=tooltip]')
            assert info and info.parent is soup.body
            assert [p.get_text() for p in info.select('p')] == [config['text']['quoteNotice'], config['text']['deliveryNotice']]
            assert panels.select_one('.shop-price-heading button[aria-controls="basket-price-info"][aria-expanded=false]')
            assert not panels.select_one('#basket-quote-notice')
            assert [link['href'] for link in panels.select('#shop-contents .toc-link')] == [
                f'#{product["id"]}' for product in catalog['products']]
            assert soup.main.find_next_sibling('footer') is soup.footer
            assert not soup.select_one('#basket-clear')
            order = soup.select_one('#order.section')
            assert 'blog-card' not in order['class']
            assert order.select_one(':scope > .contact-intro + form.terminal-form')
            assert order.select_one('.contact-intro > h2').get_text() == config['text']['checkout']
            assert not order.select('.contact-sub-1')
            assert config['text']['confirmation'] not in order.get_text()
            assert order.select_one('.mandatory-note').get_text() == config['text']['requiredFields']
            assert not order.select('label small')
            assert 'optional' not in config['text']
            for field_id, name, field_type in (('order-company', 'company', 'text'), ('order-phone', 'phone', 'tel')):
                field = order.find(id=field_id)
                assert field['name'] == name and field['type'] == field_type
                assert not field.has_attr('required')
                assert order.find('label', attrs={'for': field_id}).get_text() == config['text'][name]
            assert order.select_one('#order-street[required]')
            assert order.find('label', attrs={'for': 'order-street'}).get_text() == config['text']['street'] + ' *'
            assert order.select_one('h4#order-delivery-title.form-section-title + fieldset[aria-labelledby="order-delivery-title"]')
            assert order.select_one('h4#order-notes-title.form-section-title + textarea[aria-labelledby="order-notes-title"]')
            assert order.select_one('form[novalidate]')
            assert len(order.select('.validate-me + .warning-msg')) == 7
            main = BeautifulSoup((release / language / 'index.html').read_text(), 'html.parser')
            for page, controller in ((main, 'index.js'), (soup, 'shop.js')):
                scripts = [node['src'] for node in page.select('script[src]')]
                shared = next(src for src in scripts if '/form.js' in src)
                assert Path(shared.split('?')[0]).name == 'form.js'
                assert (release / 'form.js').is_file()
                assert scripts.index(shared) < next(i for i, src in enumerate(scripts) if f'/{controller}' in src)
            assert not order.select('#order-extra, [name="addressExtra"]')
            assert 'addressExtra' not in config['text']
            assert 'bg-loaded' in soup.body['class']
            assert any('/blog.css?' in link['href'] for link in soup.select('link[rel=stylesheet]'))
            blog = BeautifulSoup((release / language / 'blog.html').read_text(), 'html.parser')
            assert panels.select_one('#shop-toc-title').get_text() == config['text']['contentsTitle']
            assert not panels.select_one('#shop-toc-title').get_text().startswith('///')
            assert blog.select_one('.blog-sidebar .toc-title').get_text().startswith('///')
            assert not blog.select('#article-1, #post-1-title, a[href="#post-1-title"]')
            assert [heading['id'] for heading in blog.select('.blog-card h1')] == [f'post-{number}-title' for number in range(2, 9)]
            assert len(blog.select('.toc-nav a')) == 7
            assert not soup.select('a[href*="#post-1-title"]')
            public_paths = {path for lang in catalog['languages']
                            for path in (f'/{lang}', f'/{lang}/',
                                         *[f'/{lang}/{page}{suffix}' for page in ('index', 'blog', 'shop')
                                           for suffix in ('', '/', '.html')])}
            for page in (main, blog, soup):
                versioned = 0
                for link in page.select('a[href]'):
                    url = urlsplit(link['href'])
                    if (url.path in public_paths and url.scheme in ('', 'http', 'https')
                            and url.hostname in (None, 'petramuckova.cz', 'www.petramuckova.cz')):
                        assert parse_qs(url.query).get('v') == ['vshop-smoke-test'], link['href']
                        versioned += 1
                assert versioned > 0
                for link in page.select('link[rel=canonical], link[rel=alternate]'):
                    assert not urlsplit(link['href']).query
        sitemap = ET.fromstring((release / 'sitemap.xml').read_text())
        locations = sitemap.findall('{http://www.sitemaps.org/schemas/sitemap/0.9}url/{http://www.sitemaps.org/schemas/sitemap/0.9}loc')
        assert len(locations) == 30
        assert len([loc for loc in locations if loc.text.endswith('/shop.html')]) == 10
        image_locations = sitemap.findall('.//{http://www.google.com/schemas/sitemap-image/1.1}loc')
        for product in catalog['products']:
            for image in product.get('images', []):
                assert any(loc.text.endswith(image['src']) for loc in image_locations)
        assert 'eshop-placeholder.webp' not in (release / 'sitemap.xml').read_text()
    release_after = {str(p.relative_to(ROOT / 'release')): hashlib.sha256(p.read_bytes()).hexdigest()
                     for p in (ROOT / 'release').rglob('*') if p.is_file()}
    assert release_before == release_after, 'Existing release directory changed!'
    print('PASS: frontend-only isolated release, no backend/PHP/server configuration, 30 pages, CDN assets, metadata; existing release unchanged.')


if __name__ == '__main__':
    main()
